apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-doh
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  image: {{ image }}
  port: 8080
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 99%
  liveness:
    path: /isalive
  readiness:
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  kafka:
    pool: {{ kafka_pool }}
  secureLogs:
    enabled: true
  envFrom:
    - secret: credential-slack
  env:
    - name: DP_QUIZ_RETTING_URL
      value: {{dp_quiz_retting_url}}
    - name: DP_SLACKER_ALERT_CHANNEL_ID
      value: {{dp_slacker_alert_channel_id}}
    - name: DP_SLACKER_CHANNEL_ID
      value: {{dp_slacker_channel_id}}
    - name: DP_SLACKER_MAL_CHANNEL_ID
      value: {{dp_slacker_mal_channel_id}}
    - name: DP_SLACKER_VEDTAK_CHANNEL_ID
      value: {{dp_slacker_vedtak_channel_id}}
    - name: DP_ARENA_SINK_OPPRETTET_MELDING
      value: "{{dp_arena_sink_opprettet_melding}}"
    - name: JDK_JAVA_OPTIONS
      value: "-Djavax.net.debug=ssl,handshake"
  accessPolicy:
    outbound:
      external:
        - host: slack.com
        - ipv4: 3.68.124.95
        - ipv4: 52.29.238.212
        - ipv4: 3.68.175.98
        - ipv4: 18.159.197.225
        - ipv4: 3.68.124.168
        - ipv4: 3.68.170.153

        - host: logs.adeo.no
        - host: {{ DP_QUIZ_RETTING_HOST }}
