apiVersion: nais.io/v1
kind: Alert
metadata:
  name: {{app}}
  namespace: {{namespace}}
  labels:
    team: {{team}}
spec:
  alerts:
    - action: '`kubectl describe pod -l app=\{{ $labels.deployment }} -n \{{ $labels.namespace }}` for events og `kubectl get  pods -l app=\{{ $labels.deployment }} -n \{{ $labels.namespace }}` for å se feilende podder'
      alert: applikasjon nede
      description: '\{{ $labels.deployment }} har utilgjengelige podder i \{{ $labels.namespace }}'
      expr: kube_deployment_status_replicas_unavailable{deployment="{{app}}",job="kubernetes-service-endpoints"} > 0
      for: 2m

    - action: Sjekk loggene til \{{ $labels.log_app }} i \{{ $labels.log_namespace }}, for å se hvorfor det er så mye feil
      alert: høy feilrate i logger
      expr: (100 * sum by (log_app, log_namespace) (rate(logd_messages_total{log_app="{{app}}",log_level="Error"}[3m])) / sum by (log_app, log_namespace) (rate(logd_messages_total{log_app="{{app}}"}[3m]))) > 90
      for: 3m

    - action: Sjekk \{{ $labels.app }} i \{{ $labels.kubernetes_namespace }} sine selftest for å se hva som er galt
      alert: feil i selftest
      expr: selftests_aggregate_result_status{app="{{app}}"} > 0
      for: 1m

  receivers:
    slack:
      channel: '{{alerts_slack_channel}}'
      prependText: '<!here> | '
