apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-doh
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /isalive
  readiness:
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 1
    max: 6
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  secureLogs:
    enabled: true
  filesFrom:
    - secret: serviceuser-srvdp-doh
      mountPath: "/var/run/secrets/nais.io/service_user"
  envFrom:
    - secret: credential-slack
    - configmap: kafka-bootstrap-servers
  env:
    - name: KAFKA_CONSUMER_GROUP_ID
      value: dp-doh-v1
    - name: KAFKA_RAPID_TOPIC
      value: privat-dagpenger-behov-v2
    - name: DP_QUIZ_RETTING_URL
      value: {{dp_quiz_retting_url}}
    - name: KAFKA_PREFER_ON_PREM
      value: "true"
  accessPolicy:
    outbound:
      external:
        - host: slack.com
