apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-doh
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /isalive
  readiness:
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 2
    max: 6
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  kafka:
    pool: {{ kafka_pool }}
  secureLogs:
    enabled: true
  envFrom:
    - secret: credential-slack
  env:
    - name: DP_QUIZ_RETTING_URL
      value: {{dp_quiz_retting_url}}
    - name: DP_SLACKER_ALERT_CHANNEL_ID
      value: {{dp_slacker_alert_channel_id}}
    - name: DP_SLACKER_CHANNEL_ID
      value: {{dp_slacker_channel_id}}
    - name: DP_SLACKER_MAL_CHANNEL_ID
      value: {{dp_slacker_mal_channel_id}}
  accessPolicy:
    outbound:
      external:
        - host: slack.com
