apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: {{app}}
  namespace: {{namespace}}
  labels:
    team: {{team}}
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /isalive
  readiness:
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 2
    max: 3
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  secureLogs:
    enabled: true
  vault:
    enabled: true
    paths:
      - kvPath: "serviceuser/data/dev/{{service_user}}"
        mountPath: "/var/run/secrets/nais.io/service_user"
  env:
    - name: KAFKA_BOOTSTRAP_SERVERS
      value: b27apvl00045.preprod.local:8443,b27apvl00046.preprod.local:8443,b27apvl00047.preprod.local:8443
    - name: KAFKA_CONSUMER_GROUP_ID
      value: dp-doh-v1
    - name: KAFKA_RAPID_TOPIC
      value: privat-dagpenger-behov-v2